"""initial

Revision ID: c953d888e41a
Revises: 
Create Date: 2026-03-22 02:31:46.261784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c953d888e41a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('travel_front_mm', sa.Integer(), nullable=True),
    sa.Column('travel_rear_mm', sa.Integer(), nullable=True),
    sa.Column('wheel_size', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bike_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trail_name', sa.String(length=200), nullable=False),
    sa.Column('trail_condition', sa.Enum('DRY', 'TACKY', 'MUDDY', 'WET', 'MIXED', name='trail_condition'), nullable=True),
    sa.Column('weather', sa.Enum('SUNNY', 'CLOUDY', 'RAINY', 'COLD', name='weather'), nullable=True),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('front_tire_brand', sa.String(length=100), nullable=True),
    sa.Column('front_tire_model', sa.String(length=100), nullable=True),
    sa.Column('front_tire_pressure_psi', sa.Float(), nullable=True),
    sa.Column('rear_tire_brand', sa.String(length=100), nullable=True),
    sa.Column('rear_tire_model', sa.String(length=100), nullable=True),
    sa.Column('rear_tire_pressure_psi', sa.Float(), nullable=True),
    sa.Column('fork_air_pressure_psi', sa.Float(), nullable=True),
    sa.Column('fork_rebound_clicks', sa.Integer(), nullable=True),
    sa.Column('fork_compression_clicks', sa.Integer(), nullable=True),
    sa.Column('fork_tokens', sa.Integer(), nullable=True),
    sa.Column('shock_air_pressure_psi', sa.Float(), nullable=True),
    sa.Column('shock_rebound_clicks', sa.Integer(), nullable=True),
    sa.Column('shock_compression_clicks', sa.Integer(), nullable=True),
    sa.Column('shock_volume_spacers', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setups')
    op.drop_table('rides')
    op.drop_table('bikes')
    # ### end Alembic commands ###
